# docker-compose up --force-recreate --build
version: "3.9"
services:
  anti-fraude:
    build: anti-fraude
    container_name: anti-fraude
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: mongo-anti-fraude
    depends_on:
      - mongo-anti-fraude

  clientes:
    build: clientes
    container_name: clientes
    ports:
      - 3001:3001
    environment:
      MONGO_HOST: mongo-anti-fraude
    depends_on:
      - mongo-anti-fraude

  transacoes:
    build: transacoes
    container_name: transacoes
    ports:
      - 3002:3002
    environment:
      CLIENTS_HOST: clientes
      ANTI_FRAUDE_HOST: anti-fraude
      MONGO_HOST: mongo-transacoes
      MONGO_PORT: 27017
    depends_on:
      - mongo-transacoes
    # networks:
    #  - transactions-bridge

  mongo-anti-fraude:
    image: mongo
    container_name: mongo-anti-fraude
    volumes:
      - vol-mongo-anti-fraude:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-transacoes:
    image: mongo
    container_name: mongo-transacoes
    volumes:
      - vol-mongo-transacoes:/data/db
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    # networks:
    #  - transactions-bridge

volumes:
  vol-mongo-anti-fraude:
  vol-mongo-transacoes:

# networks:
#   transactions-bridge:
#     driver: bridge