openapi: 3.0.3
info:
  title: Anti Fraude API
  description: |-
    API do microsserviço de Anti Fraude
  version: 0.0.1
servers:
  - url: http://localhost:3000
paths:
  /api/antiFraud:
    get:
      summary: list Antifraud
      description: list all antifraud
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AntiFraud"
    post:
      summary: Add Antifraud
      description: Add new Antifraud
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AntiFraud"
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraud"
        '500':
          description: error
  /api/antiFraud/under-review:
    get:
      summary: list Antifraud with status under review
      description: list antifraud with status under review
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AntiFraud"
  /api/antiFraud/{id}:
    get:
      summary: Find antifraud by id
      description: Find one specific antifraud
      parameters:
        - name: id
          in: path
          description: ID of antifraud that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraud"
        '400':
          description: not found
        '500':
          description: error
    patch:
      summary: Update antifraud status
      description: Update antifraud by status under-review to approved or rejected
      parameters:
      - name: id
        in: path
        description: ID of antifraud that needs to be updated
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/AntiFraud"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraud"
        '400':
          description: not faund
        '500':
          description: error
    delete:
      summary: Delete antifraud
      description: Delete antifraud by entering its ID
      parameters:
      - name: id
        in: path
        description: ID of antifraud that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        '204':
          description: no content
        '404':
          description: not found
        '500':
          description: error
components:
  schemas:
    AntiFraud:
      type: object
      properties:
        id:
          type: string
        clientId:
          type: string
        transactionId:
          type: string
        status:
          type: string