openapi: 3.0.3
info:
  title: Anti Fraude API
  description: |-
    API do microsserviço de Anti Fraude
  version: 0.0.1
servers:
  - url: http://localhost:3000
tags:
  - name: Anti-fraude
    description: Informações sobre as analises anti-fraude
paths:
  /api/antiFraud:
    get:
      tags:
      - Anti-fraude
      summary: listar anti-fraude
      description: listar todas as analises anti-fraude
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AntiFraud"
    post:
      tags:
        - Anti-fraude
      summary: Adicionar anti-fraude
      description: criar uma analise anti-fraude com status 'Em análise' como default
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AntiFraudPost"
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraud"
        '500':
          description: error
  /api/antiFraud/under-review:
    get:
      tags:
      - Anti-fraude
      summary: listar anti-fraude com status 'em análise'
      description: listar todas as análise anti-fraude com status 'em análise'
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AntiFraud"
  /api/antiFraud/{id}:
    get:
      tags:
      - Anti-fraude
      summary: Encontar analise por id
      description: encontrar uma analise anti-fraude especifica
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
        - name: id
          in: path
          description: Id da analise anti-fraude
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraudById"
        '400':
          description: analise não encontrada
        '500':
          description: error
    patch:
      tags:
        - Anti-fraude
      summary: atualizar o status de uma analise
      description: atualizar pelo id o status da analise anti-fraude
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
        required: true
      - name: id
        in: path
        description: Id da analise que sera atualizada
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/AntiFraudStatus"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraudUpdate"
        '400':
          description: invalid ID supplied
        '401':
          description: unauthorized
    delete:
      tags:
      - Anti-fraude
      summary: Deletar analise anti-fraude
      description: Deleta uma analise pelo seu id
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
        required: true
      - name: id
        in: path
        description: Id da analise que precisa ser deletada
        required: true
        schema:
          type: string
      responses:
        '204':
          description: sucesso
        '404':
          description: analise nao encontrada
        '500':
          description: error
components:
  schemas:
    AntiFraud:
      type: object
      properties:
        id:
          type: string
          example: '649c86a6a7797f8841511dd4'
        clientId:
          type: string
          example: "649c4533100dc63fbe807107"
        transactionId:
          type: string
          example: "649c4533100dc63fbe807108"
        status:
          type: string
          example: "Em análise"
    AntiFraudPost: 
      type: object
      properties: 
        clientId:
          type: string
          example: "649c4533100dc63fbe807107"
        transactionId: 
          type: string
          example: "649c4533100dc63fbe807108"
    AntiFraudById: 
      type: object
      properties: 
        id:
          type: string
          example: '649c86a6a7797f8841511dd4' 
        status:
          type: string
          example: "Em análise"
        dadosPessoais: 
          type: object
          properties:
            nome:
              type: string
              example: "Aurora Sabrina Ramos"
            cpf:
              type: string
              example: "41286390958"
            telefone:
              type: string
              example: "6127726328"
            rendaMensal:
              type: number
              example: 7300
        Endereco:
          type: object
          properties:
            rua:
              type: string
              example: "Rua Adilson Lisboa"
            numero:
              type: string
              example: "167"
            complemento:
              type: string
              nullable: true
              example: "ap22"
            cep:
              type: string
              example: "21073090"
            cidade:
              type: string
              example: "Rio de Janeiro"
            estado:
              type: string
              enum:
              - AC
              - AL
              - AP
              - AM
              - BA
              - CE
              - DF
              - ES
              - GO
              - MA
              - MT
              - MS
              - MG
              - PA
              - PB
              - PR
              - PE
              - PI
              - RJ
              - RN
              - RS
              - RO
              - RR
              - SC
              - SP
              - SE
              - TO
              example: "RJ"
        vencimentoDaFatura:
          type: number
          example: 5
        transacao: 
          type: object
          properties: 
            id: 
              type: string
              example: '649c86a6a7797f8841511dd4'
            valor: 
              type: number
              example: 50000
    AntiFraudUpdate:
      type: object
      properties:
        id:
          type: string
          example: '649c86a6a7797f8841511dd4'
        clientId:
          type: string
          example: "649c4533100dc63fbe807107"
        transactionId:
          type: string
          example: "649c4533100dc63fbe807108"
        status:
          type: string
          example: "Aprovada"
    AntiFraudStatus: 
      type: object
      properties:
        status:
          type: string
          example: 'Em análise'